spring:
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.96.17:8848

  datasource:
    username: root
    password: root
    url: jdbc:mysql://124.223.159.109:3306/gmall_product?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 124.223.159.109
    password:
    database: 0
    port: 6379
  rabbitmq:
    host: 124.223.159.109
    port: 5672
    username: admin
    password: admin
  zipkin:
    base-url: http://47.103.96.17:9411
server:
  port: 8206
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl